### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by inomyabcs** [OpenMaine/Project-Template#1]
### Task
Have a discussion on selecting the best two licenses for OpenMaine projects to operate under. Code for America reference document for starting the discussion can be found at [https://discourse.codeforamerica.org/t/wiki-choosing-software-licenses-for-your-brigade-project/822].

### Acceptance Criteria
- [ ] Discussion opened at a Monthly Meetup
- [ ] Options for licensing decided upon by the group
- [ ] Choice is documented in the Project-Template repository for future reference for new projects.

### Notes
There is no rush to decide. A technical group may be formed to discuss the issue further and make a recommendation back to the full group.
