### ISSUE TITLE
Template Doc Update

### ISSUE THREAD

**Issue by relspeedwagon** [OpenMaine/Project-Template#2]
### Task
Many docs in the the template still refer to the original source, CodeForBaltimore, rather than OpenMaine.  OpenMaine's version of the template should be updated with our local information, and reviewed/edited to ensure all included elements are needed and reflect our process.  

### Acceptance Criteria
- [ ] All doc files have been updated with OpenMaine's information
- [ ] All files have been reviewed, any unnecessary files removed
- [ ] .md files have been reviewed, sections/headings have been edited to reflect OpenMaine's policies and any unneeded sections have been removed.

### Notes
This task likely needs input from a few people; could be a good issue to tackle in group working session/ as part of a meeting :)
